name: Build and publish a Docker image for master branch

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # Updated to v3
        with:
          platforms: 'arm64,arm' # This is for setting up emulation for multi-arch builds

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3 # Updated to v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Updated to v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6 # Updated to v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7 # Explicitly define target platforms
          push: true
          # Corrected tag format: uses DOCKERHUB_USERNAME from secrets and repository name from github context
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
